/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NucleusAccordion {
    }
    interface NucleusAccordionBody {
    }
    interface NucleusAccordionHeader {
    }
    interface NucleusAvatar {
        /**
          * @default "Avatar"
         */
        "alt": string;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default "circle"
         */
        "shape": "circle" | "square";
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "src": string;
        /**
          * @default "primary"
         */
        "type": "primary" | "secondary";
    }
    interface NucleusButton {
        /**
          * @default false
         */
        "disabled": true | false;
        /**
          * @default false
         */
        "rounded": true | false;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "type": "primary" | "secondary";
    }
    interface NucleusCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface NucleusDropdown {
        /**
          * @default ["Profile", "Logout"]
         */
        "items": string[];
        /**
          * @default "Menu"
         */
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface NucleusFooter {
        /**
          * @default "© Nucleus Design System"
         */
        "copyright": string;
    }
    interface NucleusHeader {
        /**
          * @default "Nucleus"
         */
        "brand": string;
        /**
          * @default false
         */
        "menuOpen": boolean;
    }
    interface NucleusInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "text"
         */
        "type": "text" | "email" | "password" | "search";
        /**
          * @default ""
         */
        "value": string;
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface NucleusMultiselect {
        /**
          * @default []
         */
        "options": string[];
        /**
          * @default "Select options"
         */
        "placeholder": string;
        /**
          * @default []
         */
        "value": string[];
    }
    interface NucleusPill {
        /**
          * @default false
         */
        "closed": boolean;
        /**
          * @default true
         */
        "removable": boolean;
        /**
          * @default "rounded"
         */
        "shape": "rounded" | "rectangle";
        /**
          * @default "primary"
         */
        "type": "primary" | "secondary";
    }
    interface NucleusProgress {
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default 0
         */
        "value": number;
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface NucleusRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "value": string;
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface NucleusRadioGroup {
        /**
          * @default "nucleus-radio-group"
         */
        "name": string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface NucleusTextarea {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 4
         */
        "rows": number;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "value": string;
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface NucleusToggle {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "md"
         */
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "type": "primary" | "secondary";
    }
}
export interface NucleusCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusCheckboxElement;
}
export interface NucleusDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusDropdownElement;
}
export interface NucleusHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusHeaderElement;
}
export interface NucleusInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusInputElement;
}
export interface NucleusMultiselectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusMultiselectElement;
}
export interface NucleusPillCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusPillElement;
}
export interface NucleusRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusRadioElement;
}
export interface NucleusRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusRadioGroupElement;
}
export interface NucleusTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusTextareaElement;
}
export interface NucleusToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNucleusToggleElement;
}
declare global {
    interface HTMLNucleusAccordionElement extends Components.NucleusAccordion, HTMLStencilElement {
    }
    var HTMLNucleusAccordionElement: {
        prototype: HTMLNucleusAccordionElement;
        new (): HTMLNucleusAccordionElement;
    };
    interface HTMLNucleusAccordionBodyElement extends Components.NucleusAccordionBody, HTMLStencilElement {
    }
    var HTMLNucleusAccordionBodyElement: {
        prototype: HTMLNucleusAccordionBodyElement;
        new (): HTMLNucleusAccordionBodyElement;
    };
    interface HTMLNucleusAccordionHeaderElement extends Components.NucleusAccordionHeader, HTMLStencilElement {
    }
    var HTMLNucleusAccordionHeaderElement: {
        prototype: HTMLNucleusAccordionHeaderElement;
        new (): HTMLNucleusAccordionHeaderElement;
    };
    interface HTMLNucleusAvatarElement extends Components.NucleusAvatar, HTMLStencilElement {
    }
    var HTMLNucleusAvatarElement: {
        prototype: HTMLNucleusAvatarElement;
        new (): HTMLNucleusAvatarElement;
    };
    interface HTMLNucleusButtonElement extends Components.NucleusButton, HTMLStencilElement {
    }
    var HTMLNucleusButtonElement: {
        prototype: HTMLNucleusButtonElement;
        new (): HTMLNucleusButtonElement;
    };
    interface HTMLNucleusCheckboxElementEventMap {
        "checkedChange": boolean;
    }
    interface HTMLNucleusCheckboxElement extends Components.NucleusCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusCheckboxElementEventMap>(type: K, listener: (this: HTMLNucleusCheckboxElement, ev: NucleusCheckboxCustomEvent<HTMLNucleusCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusCheckboxElementEventMap>(type: K, listener: (this: HTMLNucleusCheckboxElement, ev: NucleusCheckboxCustomEvent<HTMLNucleusCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusCheckboxElement: {
        prototype: HTMLNucleusCheckboxElement;
        new (): HTMLNucleusCheckboxElement;
    };
    interface HTMLNucleusDropdownElementEventMap {
        "dropdownToggle": boolean;
        "itemSelect": string;
    }
    interface HTMLNucleusDropdownElement extends Components.NucleusDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusDropdownElementEventMap>(type: K, listener: (this: HTMLNucleusDropdownElement, ev: NucleusDropdownCustomEvent<HTMLNucleusDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusDropdownElementEventMap>(type: K, listener: (this: HTMLNucleusDropdownElement, ev: NucleusDropdownCustomEvent<HTMLNucleusDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusDropdownElement: {
        prototype: HTMLNucleusDropdownElement;
        new (): HTMLNucleusDropdownElement;
    };
    interface HTMLNucleusFooterElement extends Components.NucleusFooter, HTMLStencilElement {
    }
    var HTMLNucleusFooterElement: {
        prototype: HTMLNucleusFooterElement;
        new (): HTMLNucleusFooterElement;
    };
    interface HTMLNucleusHeaderElementEventMap {
        "menuToggle": boolean;
        "menuClose": void;
    }
    interface HTMLNucleusHeaderElement extends Components.NucleusHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusHeaderElementEventMap>(type: K, listener: (this: HTMLNucleusHeaderElement, ev: NucleusHeaderCustomEvent<HTMLNucleusHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusHeaderElementEventMap>(type: K, listener: (this: HTMLNucleusHeaderElement, ev: NucleusHeaderCustomEvent<HTMLNucleusHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusHeaderElement: {
        prototype: HTMLNucleusHeaderElement;
        new (): HTMLNucleusHeaderElement;
    };
    interface HTMLNucleusInputElementEventMap {
        "valueChange": string;
    }
    interface HTMLNucleusInputElement extends Components.NucleusInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusInputElementEventMap>(type: K, listener: (this: HTMLNucleusInputElement, ev: NucleusInputCustomEvent<HTMLNucleusInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusInputElementEventMap>(type: K, listener: (this: HTMLNucleusInputElement, ev: NucleusInputCustomEvent<HTMLNucleusInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusInputElement: {
        prototype: HTMLNucleusInputElement;
        new (): HTMLNucleusInputElement;
    };
    interface HTMLNucleusMultiselectElementEventMap {
        "valueChange": string[];
    }
    interface HTMLNucleusMultiselectElement extends Components.NucleusMultiselect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusMultiselectElementEventMap>(type: K, listener: (this: HTMLNucleusMultiselectElement, ev: NucleusMultiselectCustomEvent<HTMLNucleusMultiselectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusMultiselectElementEventMap>(type: K, listener: (this: HTMLNucleusMultiselectElement, ev: NucleusMultiselectCustomEvent<HTMLNucleusMultiselectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusMultiselectElement: {
        prototype: HTMLNucleusMultiselectElement;
        new (): HTMLNucleusMultiselectElement;
    };
    interface HTMLNucleusPillElementEventMap {
        "pillClose": void;
    }
    interface HTMLNucleusPillElement extends Components.NucleusPill, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusPillElementEventMap>(type: K, listener: (this: HTMLNucleusPillElement, ev: NucleusPillCustomEvent<HTMLNucleusPillElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusPillElementEventMap>(type: K, listener: (this: HTMLNucleusPillElement, ev: NucleusPillCustomEvent<HTMLNucleusPillElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusPillElement: {
        prototype: HTMLNucleusPillElement;
        new (): HTMLNucleusPillElement;
    };
    interface HTMLNucleusProgressElement extends Components.NucleusProgress, HTMLStencilElement {
    }
    var HTMLNucleusProgressElement: {
        prototype: HTMLNucleusProgressElement;
        new (): HTMLNucleusProgressElement;
    };
    interface HTMLNucleusRadioElementEventMap {
        "checkedChange": string;
    }
    interface HTMLNucleusRadioElement extends Components.NucleusRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusRadioElementEventMap>(type: K, listener: (this: HTMLNucleusRadioElement, ev: NucleusRadioCustomEvent<HTMLNucleusRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusRadioElementEventMap>(type: K, listener: (this: HTMLNucleusRadioElement, ev: NucleusRadioCustomEvent<HTMLNucleusRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusRadioElement: {
        prototype: HTMLNucleusRadioElement;
        new (): HTMLNucleusRadioElement;
    };
    interface HTMLNucleusRadioGroupElementEventMap {
        "valueChange": string;
    }
    interface HTMLNucleusRadioGroupElement extends Components.NucleusRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusRadioGroupElementEventMap>(type: K, listener: (this: HTMLNucleusRadioGroupElement, ev: NucleusRadioGroupCustomEvent<HTMLNucleusRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusRadioGroupElementEventMap>(type: K, listener: (this: HTMLNucleusRadioGroupElement, ev: NucleusRadioGroupCustomEvent<HTMLNucleusRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusRadioGroupElement: {
        prototype: HTMLNucleusRadioGroupElement;
        new (): HTMLNucleusRadioGroupElement;
    };
    interface HTMLNucleusTextareaElementEventMap {
        "valueChange": string;
    }
    interface HTMLNucleusTextareaElement extends Components.NucleusTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusTextareaElementEventMap>(type: K, listener: (this: HTMLNucleusTextareaElement, ev: NucleusTextareaCustomEvent<HTMLNucleusTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusTextareaElementEventMap>(type: K, listener: (this: HTMLNucleusTextareaElement, ev: NucleusTextareaCustomEvent<HTMLNucleusTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusTextareaElement: {
        prototype: HTMLNucleusTextareaElement;
        new (): HTMLNucleusTextareaElement;
    };
    interface HTMLNucleusToggleElementEventMap {
        "switchToggle": boolean;
    }
    interface HTMLNucleusToggleElement extends Components.NucleusToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNucleusToggleElementEventMap>(type: K, listener: (this: HTMLNucleusToggleElement, ev: NucleusToggleCustomEvent<HTMLNucleusToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNucleusToggleElementEventMap>(type: K, listener: (this: HTMLNucleusToggleElement, ev: NucleusToggleCustomEvent<HTMLNucleusToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNucleusToggleElement: {
        prototype: HTMLNucleusToggleElement;
        new (): HTMLNucleusToggleElement;
    };
    interface HTMLElementTagNameMap {
        "nucleus-accordion": HTMLNucleusAccordionElement;
        "nucleus-accordion-body": HTMLNucleusAccordionBodyElement;
        "nucleus-accordion-header": HTMLNucleusAccordionHeaderElement;
        "nucleus-avatar": HTMLNucleusAvatarElement;
        "nucleus-button": HTMLNucleusButtonElement;
        "nucleus-checkbox": HTMLNucleusCheckboxElement;
        "nucleus-dropdown": HTMLNucleusDropdownElement;
        "nucleus-footer": HTMLNucleusFooterElement;
        "nucleus-header": HTMLNucleusHeaderElement;
        "nucleus-input": HTMLNucleusInputElement;
        "nucleus-multiselect": HTMLNucleusMultiselectElement;
        "nucleus-pill": HTMLNucleusPillElement;
        "nucleus-progress": HTMLNucleusProgressElement;
        "nucleus-radio": HTMLNucleusRadioElement;
        "nucleus-radio-group": HTMLNucleusRadioGroupElement;
        "nucleus-textarea": HTMLNucleusTextareaElement;
        "nucleus-toggle": HTMLNucleusToggleElement;
    }
}
declare namespace LocalJSX {
    interface NucleusAccordion {
    }
    interface NucleusAccordionBody {
    }
    interface NucleusAccordionHeader {
    }
    interface NucleusAvatar {
        /**
          * @default "Avatar"
         */
        "alt"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default "circle"
         */
        "shape"?: "circle" | "square";
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "src"?: string;
        /**
          * @default "primary"
         */
        "type"?: "primary" | "secondary";
    }
    interface NucleusButton {
        /**
          * @default false
         */
        "disabled"?: true | false;
        /**
          * @default false
         */
        "rounded"?: true | false;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "type"?: "primary" | "secondary";
    }
    interface NucleusCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCheckedChange"?: (event: NucleusCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface NucleusDropdown {
        /**
          * @default ["Profile", "Logout"]
         */
        "items"?: string[];
        /**
          * @default "Menu"
         */
        "label"?: string;
        "onDropdownToggle"?: (event: NucleusDropdownCustomEvent<boolean>) => void;
        "onItemSelect"?: (event: NucleusDropdownCustomEvent<string>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface NucleusFooter {
        /**
          * @default "© Nucleus Design System"
         */
        "copyright"?: string;
    }
    interface NucleusHeader {
        /**
          * @default "Nucleus"
         */
        "brand"?: string;
        /**
          * @default false
         */
        "menuOpen"?: boolean;
        "onMenuClose"?: (event: NucleusHeaderCustomEvent<void>) => void;
        "onMenuToggle"?: (event: NucleusHeaderCustomEvent<boolean>) => void;
    }
    interface NucleusInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "onValueChange"?: (event: NucleusInputCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "text"
         */
        "type"?: "text" | "email" | "password" | "search";
        /**
          * @default ""
         */
        "value"?: string;
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface NucleusMultiselect {
        "onValueChange"?: (event: NucleusMultiselectCustomEvent<string[]>) => void;
        /**
          * @default []
         */
        "options"?: string[];
        /**
          * @default "Select options"
         */
        "placeholder"?: string;
        /**
          * @default []
         */
        "value"?: string[];
    }
    interface NucleusPill {
        /**
          * @default false
         */
        "closed"?: boolean;
        "onPillClose"?: (event: NucleusPillCustomEvent<void>) => void;
        /**
          * @default true
         */
        "removable"?: boolean;
        /**
          * @default "rounded"
         */
        "shape"?: "rounded" | "rectangle";
        /**
          * @default "primary"
         */
        "type"?: "primary" | "secondary";
    }
    interface NucleusProgress {
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default 0
         */
        "value"?: number;
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface NucleusRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "name"?: string;
        "onCheckedChange"?: (event: NucleusRadioCustomEvent<string>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "value"?: string;
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface NucleusRadioGroup {
        /**
          * @default "nucleus-radio-group"
         */
        "name"?: string;
        "onValueChange"?: (event: NucleusRadioGroupCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface NucleusTextarea {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "onValueChange"?: (event: NucleusTextareaCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 4
         */
        "rows"?: number;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default ""
         */
        "value"?: string;
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface NucleusToggle {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onSwitchToggle"?: (event: NucleusToggleCustomEvent<boolean>) => void;
        /**
          * @default "md"
         */
        "size"?: "xs" | "sm" | "md" | "lg" | "xl";
        /**
          * @default "primary"
         */
        "type"?: "primary" | "secondary";
    }

    interface NucleusAvatarAttributes {
        "src": string;
        "alt": string;
        "name": string;
        "shape": "circle" | "square";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "type": "primary" | "secondary";
    }
    interface NucleusButtonAttributes {
        "type": "primary" | "secondary";
        "rounded": true | false;
        "disabled": true | false;
        "size": "xs" | "sm" | "md" | "lg" | "xl";
    }
    interface NucleusCheckboxAttributes {
        "checked": boolean;
        "disabled": boolean;
        "required": boolean;
        "variant": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
    }
    interface NucleusDropdownAttributes {
        "label": string;
        "open": boolean;
    }
    interface NucleusFooterAttributes {
        "copyright": string;
    }
    interface NucleusHeaderAttributes {
        "brand": string;
        "menuOpen": boolean;
    }
    interface NucleusInputAttributes {
        "value": string;
        "type": "text" | "email" | "password" | "search";
        "placeholder": string;
        "variant": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "invalid": boolean;
    }
    interface NucleusMultiselectAttributes {
        "placeholder": string;
    }
    interface NucleusPillAttributes {
        "shape": "rounded" | "rectangle";
        "type": "primary" | "secondary";
        "closed": boolean;
        "removable": boolean;
    }
    interface NucleusProgressAttributes {
        "value": number;
        "max": number;
        "variant": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "indeterminate": boolean;
    }
    interface NucleusRadioAttributes {
        "checked": boolean;
        "value": string;
        "name": string;
        "disabled": boolean;
        "required": boolean;
        "variant": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
    }
    interface NucleusRadioGroupAttributes {
        "value": string;
        "name": string;
    }
    interface NucleusTextareaAttributes {
        "value": string;
        "placeholder": string;
        "variant": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "rows": number;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "invalid": boolean;
    }
    interface NucleusToggleAttributes {
        "checked": boolean;
        "type": "primary" | "secondary";
        "size": "xs" | "sm" | "md" | "lg" | "xl";
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "nucleus-accordion": NucleusAccordion;
        "nucleus-accordion-body": NucleusAccordionBody;
        "nucleus-accordion-header": NucleusAccordionHeader;
        "nucleus-avatar": Omit<NucleusAvatar, keyof NucleusAvatarAttributes> & { [K in keyof NucleusAvatar & keyof NucleusAvatarAttributes]?: NucleusAvatar[K] } & { [K in keyof NucleusAvatar & keyof NucleusAvatarAttributes as `attr:${K}`]?: NucleusAvatarAttributes[K] } & { [K in keyof NucleusAvatar & keyof NucleusAvatarAttributes as `prop:${K}`]?: NucleusAvatar[K] };
        "nucleus-button": Omit<NucleusButton, keyof NucleusButtonAttributes> & { [K in keyof NucleusButton & keyof NucleusButtonAttributes]?: NucleusButton[K] } & { [K in keyof NucleusButton & keyof NucleusButtonAttributes as `attr:${K}`]?: NucleusButtonAttributes[K] } & { [K in keyof NucleusButton & keyof NucleusButtonAttributes as `prop:${K}`]?: NucleusButton[K] };
        "nucleus-checkbox": Omit<NucleusCheckbox, keyof NucleusCheckboxAttributes> & { [K in keyof NucleusCheckbox & keyof NucleusCheckboxAttributes]?: NucleusCheckbox[K] } & { [K in keyof NucleusCheckbox & keyof NucleusCheckboxAttributes as `attr:${K}`]?: NucleusCheckboxAttributes[K] } & { [K in keyof NucleusCheckbox & keyof NucleusCheckboxAttributes as `prop:${K}`]?: NucleusCheckbox[K] };
        "nucleus-dropdown": Omit<NucleusDropdown, keyof NucleusDropdownAttributes> & { [K in keyof NucleusDropdown & keyof NucleusDropdownAttributes]?: NucleusDropdown[K] } & { [K in keyof NucleusDropdown & keyof NucleusDropdownAttributes as `attr:${K}`]?: NucleusDropdownAttributes[K] } & { [K in keyof NucleusDropdown & keyof NucleusDropdownAttributes as `prop:${K}`]?: NucleusDropdown[K] };
        "nucleus-footer": Omit<NucleusFooter, keyof NucleusFooterAttributes> & { [K in keyof NucleusFooter & keyof NucleusFooterAttributes]?: NucleusFooter[K] } & { [K in keyof NucleusFooter & keyof NucleusFooterAttributes as `attr:${K}`]?: NucleusFooterAttributes[K] } & { [K in keyof NucleusFooter & keyof NucleusFooterAttributes as `prop:${K}`]?: NucleusFooter[K] };
        "nucleus-header": Omit<NucleusHeader, keyof NucleusHeaderAttributes> & { [K in keyof NucleusHeader & keyof NucleusHeaderAttributes]?: NucleusHeader[K] } & { [K in keyof NucleusHeader & keyof NucleusHeaderAttributes as `attr:${K}`]?: NucleusHeaderAttributes[K] } & { [K in keyof NucleusHeader & keyof NucleusHeaderAttributes as `prop:${K}`]?: NucleusHeader[K] };
        "nucleus-input": Omit<NucleusInput, keyof NucleusInputAttributes> & { [K in keyof NucleusInput & keyof NucleusInputAttributes]?: NucleusInput[K] } & { [K in keyof NucleusInput & keyof NucleusInputAttributes as `attr:${K}`]?: NucleusInputAttributes[K] } & { [K in keyof NucleusInput & keyof NucleusInputAttributes as `prop:${K}`]?: NucleusInput[K] };
        "nucleus-multiselect": Omit<NucleusMultiselect, keyof NucleusMultiselectAttributes> & { [K in keyof NucleusMultiselect & keyof NucleusMultiselectAttributes]?: NucleusMultiselect[K] } & { [K in keyof NucleusMultiselect & keyof NucleusMultiselectAttributes as `attr:${K}`]?: NucleusMultiselectAttributes[K] } & { [K in keyof NucleusMultiselect & keyof NucleusMultiselectAttributes as `prop:${K}`]?: NucleusMultiselect[K] };
        "nucleus-pill": Omit<NucleusPill, keyof NucleusPillAttributes> & { [K in keyof NucleusPill & keyof NucleusPillAttributes]?: NucleusPill[K] } & { [K in keyof NucleusPill & keyof NucleusPillAttributes as `attr:${K}`]?: NucleusPillAttributes[K] } & { [K in keyof NucleusPill & keyof NucleusPillAttributes as `prop:${K}`]?: NucleusPill[K] };
        "nucleus-progress": Omit<NucleusProgress, keyof NucleusProgressAttributes> & { [K in keyof NucleusProgress & keyof NucleusProgressAttributes]?: NucleusProgress[K] } & { [K in keyof NucleusProgress & keyof NucleusProgressAttributes as `attr:${K}`]?: NucleusProgressAttributes[K] } & { [K in keyof NucleusProgress & keyof NucleusProgressAttributes as `prop:${K}`]?: NucleusProgress[K] };
        "nucleus-radio": Omit<NucleusRadio, keyof NucleusRadioAttributes> & { [K in keyof NucleusRadio & keyof NucleusRadioAttributes]?: NucleusRadio[K] } & { [K in keyof NucleusRadio & keyof NucleusRadioAttributes as `attr:${K}`]?: NucleusRadioAttributes[K] } & { [K in keyof NucleusRadio & keyof NucleusRadioAttributes as `prop:${K}`]?: NucleusRadio[K] };
        "nucleus-radio-group": Omit<NucleusRadioGroup, keyof NucleusRadioGroupAttributes> & { [K in keyof NucleusRadioGroup & keyof NucleusRadioGroupAttributes]?: NucleusRadioGroup[K] } & { [K in keyof NucleusRadioGroup & keyof NucleusRadioGroupAttributes as `attr:${K}`]?: NucleusRadioGroupAttributes[K] } & { [K in keyof NucleusRadioGroup & keyof NucleusRadioGroupAttributes as `prop:${K}`]?: NucleusRadioGroup[K] };
        "nucleus-textarea": Omit<NucleusTextarea, keyof NucleusTextareaAttributes> & { [K in keyof NucleusTextarea & keyof NucleusTextareaAttributes]?: NucleusTextarea[K] } & { [K in keyof NucleusTextarea & keyof NucleusTextareaAttributes as `attr:${K}`]?: NucleusTextareaAttributes[K] } & { [K in keyof NucleusTextarea & keyof NucleusTextareaAttributes as `prop:${K}`]?: NucleusTextarea[K] };
        "nucleus-toggle": Omit<NucleusToggle, keyof NucleusToggleAttributes> & { [K in keyof NucleusToggle & keyof NucleusToggleAttributes]?: NucleusToggle[K] } & { [K in keyof NucleusToggle & keyof NucleusToggleAttributes as `attr:${K}`]?: NucleusToggleAttributes[K] } & { [K in keyof NucleusToggle & keyof NucleusToggleAttributes as `prop:${K}`]?: NucleusToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nucleus-accordion": LocalJSX.IntrinsicElements["nucleus-accordion"] & JSXBase.HTMLAttributes<HTMLNucleusAccordionElement>;
            "nucleus-accordion-body": LocalJSX.IntrinsicElements["nucleus-accordion-body"] & JSXBase.HTMLAttributes<HTMLNucleusAccordionBodyElement>;
            "nucleus-accordion-header": LocalJSX.IntrinsicElements["nucleus-accordion-header"] & JSXBase.HTMLAttributes<HTMLNucleusAccordionHeaderElement>;
            "nucleus-avatar": LocalJSX.IntrinsicElements["nucleus-avatar"] & JSXBase.HTMLAttributes<HTMLNucleusAvatarElement>;
            "nucleus-button": LocalJSX.IntrinsicElements["nucleus-button"] & JSXBase.HTMLAttributes<HTMLNucleusButtonElement>;
            "nucleus-checkbox": LocalJSX.IntrinsicElements["nucleus-checkbox"] & JSXBase.HTMLAttributes<HTMLNucleusCheckboxElement>;
            "nucleus-dropdown": LocalJSX.IntrinsicElements["nucleus-dropdown"] & JSXBase.HTMLAttributes<HTMLNucleusDropdownElement>;
            "nucleus-footer": LocalJSX.IntrinsicElements["nucleus-footer"] & JSXBase.HTMLAttributes<HTMLNucleusFooterElement>;
            "nucleus-header": LocalJSX.IntrinsicElements["nucleus-header"] & JSXBase.HTMLAttributes<HTMLNucleusHeaderElement>;
            "nucleus-input": LocalJSX.IntrinsicElements["nucleus-input"] & JSXBase.HTMLAttributes<HTMLNucleusInputElement>;
            "nucleus-multiselect": LocalJSX.IntrinsicElements["nucleus-multiselect"] & JSXBase.HTMLAttributes<HTMLNucleusMultiselectElement>;
            "nucleus-pill": LocalJSX.IntrinsicElements["nucleus-pill"] & JSXBase.HTMLAttributes<HTMLNucleusPillElement>;
            "nucleus-progress": LocalJSX.IntrinsicElements["nucleus-progress"] & JSXBase.HTMLAttributes<HTMLNucleusProgressElement>;
            "nucleus-radio": LocalJSX.IntrinsicElements["nucleus-radio"] & JSXBase.HTMLAttributes<HTMLNucleusRadioElement>;
            "nucleus-radio-group": LocalJSX.IntrinsicElements["nucleus-radio-group"] & JSXBase.HTMLAttributes<HTMLNucleusRadioGroupElement>;
            "nucleus-textarea": LocalJSX.IntrinsicElements["nucleus-textarea"] & JSXBase.HTMLAttributes<HTMLNucleusTextareaElement>;
            "nucleus-toggle": LocalJSX.IntrinsicElements["nucleus-toggle"] & JSXBase.HTMLAttributes<HTMLNucleusToggleElement>;
        }
    }
}
