"use client";

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from "@stencil/react-output-target/runtime";
import { createComponent } from "@stencil/react-output-target/runtime";
import {
  type NucleusCheckboxCustomEvent,
  type NucleusDropdownCustomEvent,
  type NucleusHeaderCustomEvent,
  type NucleusInputCustomEvent,
  type NucleusMultiselectCustomEvent,
  type NucleusPillCustomEvent,
  type NucleusRadioCustomEvent,
  type NucleusRadioGroupCustomEvent,
  type NucleusTextareaCustomEvent,
  type NucleusToggleCustomEvent,
} from "nucleus";
import {
  NucleusAccordionBody as NucleusAccordionBodyElement,
  defineCustomElement as defineNucleusAccordionBody,
} from "nucleus/components/nucleus-accordion-body.js";
import {
  NucleusAccordionHeader as NucleusAccordionHeaderElement,
  defineCustomElement as defineNucleusAccordionHeader,
} from "nucleus/components/nucleus-accordion-header.js";
import {
  NucleusAccordion as NucleusAccordionElement,
  defineCustomElement as defineNucleusAccordion,
} from "nucleus/components/nucleus-accordion.js";
import {
  NucleusAvatar as NucleusAvatarElement,
  defineCustomElement as defineNucleusAvatar,
} from "nucleus/components/nucleus-avatar.js";
import {
  NucleusButton as NucleusButtonElement,
  defineCustomElement as defineNucleusButton,
} from "nucleus/components/nucleus-button.js";
import {
  NucleusCheckbox as NucleusCheckboxElement,
  defineCustomElement as defineNucleusCheckbox,
} from "nucleus/components/nucleus-checkbox.js";
import {
  NucleusDropdown as NucleusDropdownElement,
  defineCustomElement as defineNucleusDropdown,
} from "nucleus/components/nucleus-dropdown.js";
import {
  NucleusFooter as NucleusFooterElement,
  defineCustomElement as defineNucleusFooter,
} from "nucleus/components/nucleus-footer.js";
import {
  NucleusHeader as NucleusHeaderElement,
  defineCustomElement as defineNucleusHeader,
} from "nucleus/components/nucleus-header.js";
import {
  NucleusInput as NucleusInputElement,
  defineCustomElement as defineNucleusInput,
} from "nucleus/components/nucleus-input.js";
import {
  NucleusMultiselect as NucleusMultiselectElement,
  defineCustomElement as defineNucleusMultiselect,
} from "nucleus/components/nucleus-multiselect.js";
import {
  NucleusPill as NucleusPillElement,
  defineCustomElement as defineNucleusPill,
} from "nucleus/components/nucleus-pill.js";
import {
  NucleusProgress as NucleusProgressElement,
  defineCustomElement as defineNucleusProgress,
} from "nucleus/components/nucleus-progress.js";
import {
  NucleusRadioGroup as NucleusRadioGroupElement,
  defineCustomElement as defineNucleusRadioGroup,
} from "nucleus/components/nucleus-radio-group.js";
import {
  NucleusRadio as NucleusRadioElement,
  defineCustomElement as defineNucleusRadio,
} from "nucleus/components/nucleus-radio.js";
import {
  NucleusTextarea as NucleusTextareaElement,
  defineCustomElement as defineNucleusTextarea,
} from "nucleus/components/nucleus-textarea.js";
import {
  NucleusToggle as NucleusToggleElement,
  defineCustomElement as defineNucleusToggle,
} from "nucleus/components/nucleus-toggle.js";
import React from "react";

export type NucleusAccordionEvents = NonNullable<unknown>;

export const NucleusAccordion: StencilReactComponent<NucleusAccordionElement, NucleusAccordionEvents> =
  /*@__PURE__*/ createComponent<NucleusAccordionElement, NucleusAccordionEvents>({
    tagName: "nucleus-accordion",
    elementClass: NucleusAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusAccordionEvents,
    defineCustomElement: defineNucleusAccordion,
  });

export type NucleusAccordionBodyEvents = NonNullable<unknown>;

export const NucleusAccordionBody: StencilReactComponent<NucleusAccordionBodyElement, NucleusAccordionBodyEvents> =
  /*@__PURE__*/ createComponent<NucleusAccordionBodyElement, NucleusAccordionBodyEvents>({
    tagName: "nucleus-accordion-body",
    elementClass: NucleusAccordionBodyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusAccordionBodyEvents,
    defineCustomElement: defineNucleusAccordionBody,
  });

export type NucleusAccordionHeaderEvents = NonNullable<unknown>;

export const NucleusAccordionHeader: StencilReactComponent<
  NucleusAccordionHeaderElement,
  NucleusAccordionHeaderEvents
> = /*@__PURE__*/ createComponent<NucleusAccordionHeaderElement, NucleusAccordionHeaderEvents>({
  tagName: "nucleus-accordion-header",
  elementClass: NucleusAccordionHeaderElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {} as NucleusAccordionHeaderEvents,
  defineCustomElement: defineNucleusAccordionHeader,
});

export type NucleusAvatarEvents = NonNullable<unknown>;

export const NucleusAvatar: StencilReactComponent<NucleusAvatarElement, NucleusAvatarEvents> =
  /*@__PURE__*/ createComponent<NucleusAvatarElement, NucleusAvatarEvents>({
    tagName: "nucleus-avatar",
    elementClass: NucleusAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusAvatarEvents,
    defineCustomElement: defineNucleusAvatar,
  });

export type NucleusButtonEvents = NonNullable<unknown>;

export const NucleusButton: StencilReactComponent<NucleusButtonElement, NucleusButtonEvents> =
  /*@__PURE__*/ createComponent<NucleusButtonElement, NucleusButtonEvents>({
    tagName: "nucleus-button",
    elementClass: NucleusButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusButtonEvents,
    defineCustomElement: defineNucleusButton,
  });

export type NucleusCheckboxEvents = { onCheckedChange: EventName<NucleusCheckboxCustomEvent<boolean>> };

export const NucleusCheckbox: StencilReactComponent<NucleusCheckboxElement, NucleusCheckboxEvents> =
  /*@__PURE__*/ createComponent<NucleusCheckboxElement, NucleusCheckboxEvents>({
    tagName: "nucleus-checkbox",
    elementClass: NucleusCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCheckedChange: "checkedChange" } as NucleusCheckboxEvents,
    defineCustomElement: defineNucleusCheckbox,
  });

export type NucleusDropdownEvents = {
  onDropdownToggle: EventName<NucleusDropdownCustomEvent<boolean>>;
  onItemSelect: EventName<NucleusDropdownCustomEvent<string>>;
};

export const NucleusDropdown: StencilReactComponent<NucleusDropdownElement, NucleusDropdownEvents> =
  /*@__PURE__*/ createComponent<NucleusDropdownElement, NucleusDropdownEvents>({
    tagName: "nucleus-dropdown",
    elementClass: NucleusDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onDropdownToggle: "dropdownToggle",
      onItemSelect: "itemSelect",
    } as NucleusDropdownEvents,
    defineCustomElement: defineNucleusDropdown,
  });

export type NucleusFooterEvents = NonNullable<unknown>;

export const NucleusFooter: StencilReactComponent<NucleusFooterElement, NucleusFooterEvents> =
  /*@__PURE__*/ createComponent<NucleusFooterElement, NucleusFooterEvents>({
    tagName: "nucleus-footer",
    elementClass: NucleusFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusFooterEvents,
    defineCustomElement: defineNucleusFooter,
  });

export type NucleusHeaderEvents = {
  onMenuToggle: EventName<NucleusHeaderCustomEvent<boolean>>;
  onMenuClose: EventName<NucleusHeaderCustomEvent<void>>;
};

export const NucleusHeader: StencilReactComponent<NucleusHeaderElement, NucleusHeaderEvents> =
  /*@__PURE__*/ createComponent<NucleusHeaderElement, NucleusHeaderEvents>({
    tagName: "nucleus-header",
    elementClass: NucleusHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onMenuToggle: "menuToggle",
      onMenuClose: "menuClose",
    } as NucleusHeaderEvents,
    defineCustomElement: defineNucleusHeader,
  });

export type NucleusInputEvents = { onValueChange: EventName<NucleusInputCustomEvent<string>> };

export const NucleusInput: StencilReactComponent<NucleusInputElement, NucleusInputEvents> =
  /*@__PURE__*/ createComponent<NucleusInputElement, NucleusInputEvents>({
    tagName: "nucleus-input",
    elementClass: NucleusInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: "valueChange" } as NucleusInputEvents,
    defineCustomElement: defineNucleusInput,
  });

export type NucleusMultiselectEvents = { onValueChange: EventName<NucleusMultiselectCustomEvent<string[]>> };

export const NucleusMultiselect: StencilReactComponent<NucleusMultiselectElement, NucleusMultiselectEvents> =
  /*@__PURE__*/ createComponent<NucleusMultiselectElement, NucleusMultiselectEvents>({
    tagName: "nucleus-multiselect",
    elementClass: NucleusMultiselectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: "valueChange" } as NucleusMultiselectEvents,
    defineCustomElement: defineNucleusMultiselect,
  });

export type NucleusPillEvents = { onPillClose: EventName<NucleusPillCustomEvent<void>> };

export const NucleusPill: StencilReactComponent<NucleusPillElement, NucleusPillEvents> = /*@__PURE__*/ createComponent<
  NucleusPillElement,
  NucleusPillEvents
>({
  tagName: "nucleus-pill",
  elementClass: NucleusPillElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: { onPillClose: "pillClose" } as NucleusPillEvents,
  defineCustomElement: defineNucleusPill,
});

export type NucleusProgressEvents = NonNullable<unknown>;

export const NucleusProgress: StencilReactComponent<NucleusProgressElement, NucleusProgressEvents> =
  /*@__PURE__*/ createComponent<NucleusProgressElement, NucleusProgressEvents>({
    tagName: "nucleus-progress",
    elementClass: NucleusProgressElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as NucleusProgressEvents,
    defineCustomElement: defineNucleusProgress,
  });

export type NucleusRadioEvents = { onCheckedChange: EventName<NucleusRadioCustomEvent<string>> };

export const NucleusRadio: StencilReactComponent<NucleusRadioElement, NucleusRadioEvents> =
  /*@__PURE__*/ createComponent<NucleusRadioElement, NucleusRadioEvents>({
    tagName: "nucleus-radio",
    elementClass: NucleusRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCheckedChange: "checkedChange" } as NucleusRadioEvents,
    defineCustomElement: defineNucleusRadio,
  });

export type NucleusRadioGroupEvents = { onValueChange: EventName<NucleusRadioGroupCustomEvent<string>> };

export const NucleusRadioGroup: StencilReactComponent<NucleusRadioGroupElement, NucleusRadioGroupEvents> =
  /*@__PURE__*/ createComponent<NucleusRadioGroupElement, NucleusRadioGroupEvents>({
    tagName: "nucleus-radio-group",
    elementClass: NucleusRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: "valueChange" } as NucleusRadioGroupEvents,
    defineCustomElement: defineNucleusRadioGroup,
  });

export type NucleusTextareaEvents = { onValueChange: EventName<NucleusTextareaCustomEvent<string>> };

export const NucleusTextarea: StencilReactComponent<NucleusTextareaElement, NucleusTextareaEvents> =
  /*@__PURE__*/ createComponent<NucleusTextareaElement, NucleusTextareaEvents>({
    tagName: "nucleus-textarea",
    elementClass: NucleusTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: "valueChange" } as NucleusTextareaEvents,
    defineCustomElement: defineNucleusTextarea,
  });

export type NucleusToggleEvents = { onSwitchToggle: EventName<NucleusToggleCustomEvent<boolean>> };

export const NucleusToggle: StencilReactComponent<NucleusToggleElement, NucleusToggleEvents> =
  /*@__PURE__*/ createComponent<NucleusToggleElement, NucleusToggleEvents>({
    tagName: "nucleus-toggle",
    elementClass: NucleusToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSwitchToggle: "switchToggle" } as NucleusToggleEvents,
    defineCustomElement: defineNucleusToggle,
  });
